"use client";

import Image from "next/image";
import Link from "next/link";
import { Heart, Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";
import { getCartPreviewPrice, useCart } from "@/lib/cart/cart-context";
import { CartInterestHandoff } from "@/components/cart/CartInterestHandoff";

export function CartPage() {
  const cart = useCart();
  if (!cart.products.length) return <div className="min-h-screen bg-[var(--co-cream)] px-4 pb-16 pt-28 md:px-8 md:pt-36"><section className="mx-auto max-w-[720px] rounded-[32px] border border-black/[.07] bg-white/70 px-6 py-14 text-center shadow-[0_20px_56px_rgba(58,36,22,.07)]"><span className="mx-auto grid size-14 place-items-center rounded-full bg-[#e5f0df] text-[#214d2b]"><ShoppingBag size={23}/></span><p className="co-label mt-6 text-[#214d2b]">Your .CO shelf</p><h1 className="mt-3 font-['Cormorant_Garamond'] text-5xl leading-none text-[#2a1b13]">Your cart is waiting.</h1><p className="mx-auto mt-4 max-w-md text-sm leading-6 text-[#695e55]">Add a coconut favourite and it will be ready here when you are.</p><Link href="/shop" className="co-auth-primary mt-7 max-w-xs">Continue shopping</Link></section></div>;
  return <div className="min-h-screen bg-[var(--co-cream)] px-4 pb-16 pt-28 md:px-8 md:pb-24 md:pt-36"><div className="mx-auto max-w-[1180px]"><header className="mb-6"><p className="co-label text-[#214d2b]">Your .CO shelf</p><h1 className="mt-3 font-['Cormorant_Garamond'] text-[clamp(3.5rem,8vw,6.25rem)] leading-[.82] tracking-[-.045em] text-[#2a1b13]">Cart.</h1><p className="mt-4 text-sm text-[#695e55]">Keep a shortlist, then choose how you want .CO to follow up.</p></header><div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><section className="space-y-3">{cart.products.map((product) => <article key={product.cartKey} className="grid grid-cols-[92px_1fr] gap-4 rounded-[26px] border border-black/[.07] bg-white/70 p-3 shadow-[0_10px_26px_rgba(58,36,22,.04)] sm:grid-cols-[112px_1fr_auto] sm:items-center sm:p-4"><div className="relative aspect-square overflow-hidden rounded-[20px] bg-[#f6f0e7]"><Image src={product.image} alt={product.name} fill sizes="112px" className="object-contain p-2"/></div><div><p className="text-xs font-semibold uppercase tracking-[.11em] text-[#6c6258]">{product.variantLabel ?? product.category}</p><h2 className="mt-2 font-['Cormorant_Garamond'] text-3xl leading-none text-[#2a1b13]">{product.name}</h2><p className="mt-2 text-sm font-semibold text-[#214d2b]">₹{(product.unitPrice ?? getCartPreviewPrice(product.slug)).toLocaleString("en-IN")}</p><div className="mt-4 flex items-center gap-2"><button aria-label={`Decrease ${product.name}`} onClick={() => cart.updateQuantity(product.cartKey, product.quantity - 1)} className="grid size-8 place-items-center rounded-full border border-black/10"><Minus size={14}/></button><span className="grid size-8 place-items-center text-sm font-semibold">{product.quantity}</span><button aria-label={`Increase ${product.name}`} onClick={() => cart.updateQuantity(product.cartKey, product.quantity + 1)} className="grid size-8 place-items-center rounded-full bg-[#214d2b] text-white"><Plus size={14}/></button></div></div><div className="col-start-2 flex items-center justify-between sm:col-start-auto sm:flex-col sm:items-end sm:gap-7"><button type="button" onClick={() => cart.removeItem(product.cartKey)} className="inline-flex items-center gap-2 text-xs font-semibold text-[#7b2e25] hover:underline"><Trash2 size={14}/>Remove</button><button type="button" className="inline-flex items-center gap-2 text-xs font-semibold text-[#214d2b] hover:underline"><Heart size={14}/>Save for later</button></div></article>)}</section><aside className="h-fit lg:sticky lg:top-28"><CartInterestHandoff productSlugs={cart.products.map((product) => product.slug)} productCategories={cart.products.map((product) => product.category)}/><Link href="/shop" className="mt-4 block text-center text-sm font-semibold text-[#214d2b] underline underline-offset-4">Continue shopping</Link></aside></div></div></div>;
}
