"use client";
import { useEffect, useRef, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Bell, Check, CreditCard, Home, LockKeyhole, MapPin, Monitor, Pencil, Plus, ShieldCheck, Trash2 } from "lucide-react";
import type { AccountData, AccountAddress } from "@/lib/account/data";
import type { CustomerSession } from "@/lib/customer/auth-config";
import { saveAccountAddress, removeAccountAddress, saveAccountPreferences } from "@/lib/account/actions";
import { deleteCustomerAccount, logoutCustomer } from "@/lib/customer/actions";
import { productCategories } from "@/lib/catalog";
import { ActionLink, EmptyCard, Panel, Promo, Unavailable } from "./AccountShell";
const addressFields = [{name:"fullName",label:"Recipient name",min:2,max:100,complete:"name"},{name:"phone",label:"Phone number",min:7,max:20,complete:"tel"},{name:"line1",label:"Address line 1",min:3,max:160,complete:"address-line1"},{name:"line2",label:"Address line 2 (optional)",min:0,max:160,complete:"address-line2"},{name:"city",label:"City",min:2,max:80,complete:"address-level2"},{name:"region",label:"State / region",min:2,max:80,complete:"address-level1"},{name:"postalCode",label:"Postal code",min:3,max:16,complete:"postal-code"},{name:"country",label:"Country code (IN, for example)",min:2,max:2,complete:"country"}] as const;
export function AddressBook({data}:{data:AccountData}) {
 const router=useRouter();const guard=useRef(new Set<string>());const [addresses,setAddresses]=useState(data.addresses);const [editing,setEditing]=useState<AccountAddress|"new"|null>(null);const [deleting,setDeleting]=useState<string|null>(null);const [message,setMessage]=useState("");const [pending,startTransition]=useTransition();
 useEffect(()=>setAddresses(data.addresses),[data.addresses]);
 function save(form:HTMLFormElement){const key="address:save";if(guard.current.has(key))return;guard.current.add(key);const fields=Object.fromEntries(new FormData(form));startTransition(async()=>{try{const result=await saveAccountAddress({...fields,isDefault:fields.isDefault==="on"},editing&&editing!=="new"?editing.addressId:undefined);setMessage(result.message);if(result.ok){setEditing(null);router.refresh();}}finally{guard.current.delete(key);}});}
 return <><div className="ac-columns"><Panel title="Saved addresses" action={<button className="ac-button" disabled={data.unavailable.addresses} onClick={()=>{setEditing("new");setMessage("");}}><Plus size={17}/>Add new address</button>}>
  <p className="ac-muted">Manage your delivery addresses for a smoother checkout.</p>{data.unavailable.addresses&&<Unavailable>We couldn’t load your saved addresses. Refresh the page to try again.</Unavailable>}<p role="status" className="ac-feedback">{message}</p>
  {editing&&<form className="ac-address-form" onSubmit={event=>{event.preventDefault();save(event.currentTarget);}}><h3>{editing==="new"?"Add an address":"Edit address"}</h3><div className="ac-fields">{addressFields.map(field=><label key={field.name}>{field.label}<input name={field.name} type={field.name==="phone"?"tel":"text"} autoComplete={field.complete} minLength={field.min||undefined} maxLength={field.max} required={field.name!=="line2"} defaultValue={editing!=="new"?editing[field.name]:field.name==="country"?"IN":""}/></label>)}</div><label className="ac-check"><input type="checkbox" name="isDefault" defaultChecked={editing!=="new"&&editing.isDefault}/>Mark as a preferred delivery address</label><div className="ac-actions"><button className="ac-button" disabled={pending}>{pending?"Saving…":"Save address"}</button><button type="button" className="ac-text-link" disabled={pending} onClick={()=>setEditing(null)}>Cancel</button></div></form>}
  <div className="ac-address-list">{addresses.map(address=><article key={address.addressId} className={`ac-address ${address.isDefault?"ac-address--default":""}`}><div className="ac-icon-orbit"><Home size={24}/></div><div><h3>{address.fullName}{address.isDefault&&<span className="ac-badge">Preferred</span>}</h3><address>{address.line1}<br/>{address.line2&&<>{address.line2}<br/></>}{address.city}, {address.region} {address.postalCode}<br/>{address.country}<br/>{address.phone}</address></div><div className="ac-address-tools"><button disabled={pending} onClick={()=>{setEditing(address);setMessage("");}}><Pencil size={17}/>Edit</button><button disabled={pending} onClick={()=>setDeleting(address.addressId)}><Trash2 size={17}/>Delete</button><p><MapPin size={22}/>Your essentials, closer to home.</p>{deleting===address.addressId&&<div className="ac-delete-confirm" role="group" aria-label="Confirm address deletion"><p>Remove this saved address?</p><button disabled={pending} onClick={()=>{const key=`address:delete:${address.addressId}`;if(guard.current.has(key))return;guard.current.add(key);startTransition(async()=>{try{const result=await removeAccountAddress(address.addressId);setMessage(result.message);if(result.ok){setAddresses(items=>items.filter(item=>item.addressId!==address.addressId));setDeleting(null);router.refresh();}}finally{guard.current.delete(key);}});}}>Confirm removal</button><button disabled={pending} onClick={()=>setDeleting(null)}>Keep address</button></div>}</div></article>)}</div>
  {!addresses.length&&!editing&&!data.unavailable.addresses&&<EmptyCard title="No addresses yet" body="Save your delivery details, ready for your next coconut moment." href="#add-address" action="Add your first address" scene={3}/>}{!addresses.length&&!editing&&!data.unavailable.addresses&&<button id="add-address" className="ac-button ac-spaced" onClick={()=>setEditing("new")}><Plus size={18}/>Add an address</button>}
 </Panel><div className="ac-stack"><Promo title="Wellness finds its way home." body="Wherever your day takes you, keep your coconut favourites close." scene={3} className="ac-promo--tall"/><Panel title="A thoughtful delivery"><div className="ac-value"><Home/><div><h3>Ready when you are</h3><p>Save your details once. Find them here whenever you need them.</p></div></div><div className="ac-value"><ShieldCheck/><div><h3>Your details, your choice</h3><p>Review, update or remove an address at any time.</p></div></div></Panel></div></div><Panel title="Make every order smoother"><div className="ac-benefits"><div><h3>Less typing</h3><p>Your delivery details in one place.</p></div><div><h3>Accurate delivery</h3><p>Keep your address up to date.</p></div><div><h3>A more mindful you</h3><p>More time for what nourishes you.</p></div></div></Panel><Promo title="Goodness goes further." body="Same trusted products. Now closer to you." scene={3}/></>;
}
export function Preferences({data,session}:{data:AccountData;session:CustomerSession}) {
 const profile=data.profile;const guard=useRef(false);const [message,setMessage]=useState("");const [pending,startTransition]=useTransition();const [motion,setMotion]=useState(false);const [large,setLarge]=useState(false);
 function submit(form:HTMLFormElement){if(guard.current)return;guard.current=true;const f=Object.fromEntries(new FormData(form));startTransition(async()=>{try{const result=await saveAccountPreferences({firstName:f.firstName,lastName:f.lastName,displayName:f.displayName,phone:f.phone,preferredCategory:f.preferredCategory,newsletterOptIn:f.newsletterOptIn==="on",marketingOptIn:f.marketingOptIn==="on",address:{line1:f.profileLine1,line2:f.profileLine2,city:f.profileCity,region:f.profileRegion,postalCode:f.profilePostalCode,country:f.profileCountry}});setMessage(result.message);}finally{guard.current=false;}});}
 return <div className={`ac-settings ${large?"ac-settings--large":""} ${motion?"ac-reduce-motion":""}`}><aside className="ac-member-sidebar"><div className="ac-avatar">{session.initials}</div><h2>{profile?.displayName||session.name}</h2><p>Your personal .CO space</p><nav aria-label="Preference sections">{[["Profile & account","profile-information"],["Communication","communication"],["Delivery preferences","delivery"],["Payment preferences","payment"],["Accessibility","accessibility"]].map(([label,id])=><a href={`#${id}`} key={id}>{label}</a>)}</nav><Promo title="A more nourishing tomorrow" body="Your choices make a difference." href="/sustainability" action="Explore our story" scene={5}/></aside><div className="ac-stack"><div className="ac-intro-strip">A more personal .CO experience.<span>Saved preferences · Thoughtful choices</span></div>{data.unavailable.profile&&<Unavailable>Your profile couldn’t be loaded. Please refresh before editing.</Unavailable>}
 <form onSubmit={e=>{e.preventDefault();submit(e.currentTarget);}} className="ac-stack"><Panel title="Profile information" className="ac-profile-form"><div id="profile-information" className="ac-profile-summary"><div className="ac-avatar">{session.initials}</div><div><h3>{profile?.displayName||session.name}</h3><p>{session.email}</p>{session.emailVerified&&<span className="ac-badge ac-badge--green"><Check size={13}/>Email verified</span>}</div></div><fieldset disabled={data.unavailable.profile||pending}><div className="ac-fields">{[{name:"firstName",label:"First name",value:profile?.firstName??session.name.split(" ")[0]},{name:"lastName",label:"Last name",value:profile?.lastName??session.name.split(" ").slice(1).join(" ")},{name:"displayName",label:"Display name",value:profile?.displayName??session.name},{name:"phone",label:"Phone number",value:profile?.phone??""}].map(f=><label key={f.name}>{f.label}<input name={f.name} defaultValue={f.value} type={f.name==="phone"?"tel":"text"} maxLength={f.name==="phone"?20:f.name==="displayName"?80:60} required={f.name==="displayName"} minLength={f.name==="displayName"?2:undefined}/></label>)}<label>Product interest<select name="preferredCategory" defaultValue={profile?.preferredCategory??productCategories[0]}>{productCategories.map(c=><option key={c}>{c}</option>)}</select></label></div></fieldset></Panel>
 <div className="ac-two-up"><Panel title="Change password"><LockKeyhole className="ac-feature-icon"/><h3>Keep your account secure.</h3><p>Reset your password using the verified recovery flow.</p><ActionLink href={`/forgot-password?email=${encodeURIComponent(session.email)}`}>Change password</ActionLink></Panel><Panel title="Two-factor authentication"><ShieldCheck className="ac-feature-icon"/><h3>An extra layer of care.</h3><p>Two-factor setup is not available in your account yet.</p><ActionLink href="/contact" secondary>Account support</ActionLink></Panel></div>
 <Panel title="Delivery profile"><div id="delivery"><p>Keep the delivery address already stored with your customer profile current. Your reusable address book remains available separately.</p><fieldset disabled={data.unavailable.profile||pending}><div className="ac-fields"><label>Address line 1<input name="profileLine1" maxLength={160} defaultValue={profile?.address?.line1??""}/></label><label>Address line 2<input name="profileLine2" maxLength={160} defaultValue={profile?.address?.line2??""}/></label><label>City<input name="profileCity" maxLength={80} defaultValue={profile?.address?.city??""}/></label><label>State / region<input name="profileRegion" maxLength={80} defaultValue={profile?.address?.region??""}/></label><label>Postal code<input name="profilePostalCode" maxLength={16} defaultValue={profile?.address?.postalCode??""}/></label><label>Country<input name="profileCountry" maxLength={80} defaultValue={profile?.address?.country??"India"}/></label></div></fieldset></div></Panel>
 <Panel title="Communication preferences"><div id="communication"><p>Choose what you’d like to hear about.</p><fieldset disabled={data.unavailable.profile||pending}><label className="ac-toggle-row"><span>Product notes & recipes<small>New .CO products and ideas from our kitchen.</small></span><input role="switch" type="checkbox" name="newsletterOptIn" defaultChecked={profile?.newsletterOptIn??false}/></label><label className="ac-toggle-row"><span>Launch & member offers<small>Hear about new launches and member offers.</small></span><input role="switch" type="checkbox" name="marketingOptIn" defaultChecked={profile?.marketingOptIn??false}/></label></fieldset><div className="ac-actions"><button className="ac-button" disabled={pending||data.unavailable.profile}>{pending?"Saving…":"Save preferences"}<Check size={16}/></button><p role="status" className="ac-feedback">{message}</p></div></div></Panel></form>
 <div className="ac-two-up"><Panel title="Saved address book"><div><Home className="ac-feature-icon"/><h3>Your saved addresses</h3><p>{data.unavailable.addresses?"Saved address count is currently unavailable.":`${data.addresses.length} saved ${data.addresses.length===1?"address":"addresses"}.`}</p><ActionLink href="/account/addresses">Manage addresses</ActionLink></div></Panel><Panel title="Payment preferences"><div id="payment"><CreditCard className="ac-feature-icon"/><h3>Thoughtfully handled.</h3><p>Live payments and saved payment methods are not yet available.</p><ActionLink href="/account/payments">View payment information</ActionLink></div></Panel></div>
 <Panel title="Accessibility"><div id="accessibility"><p>Adjust this settings page for comfortable reading.</p><label className="ac-toggle-row"><span>Larger text<small>Increase text size on this settings page.</small></span><input type="checkbox" role="switch" checked={large} onChange={e=>setLarge(e.target.checked)}/></label><label className="ac-toggle-row"><span>Reduce toggle motion<small>Your device’s reduced-motion preference is always respected.</small></span><input type="checkbox" role="switch" checked={motion} onChange={e=>setMotion(e.target.checked)}/></label></div></Panel><Panel title="Account controls"><details><summary>Delete your account</summary><form action={deleteCustomerAccount} className="ac-delete-form"><p>Type DELETE to permanently remove your customer profile.</p><label>Confirmation<input name="confirmation" required pattern="DELETE" aria-label="Type DELETE to confirm"/></label><button className="ac-button">Delete account</button></form></details></Panel>
 </div></div>;
}
export function Security({session}:{session:CustomerSession}) {return <div className="ac-columns"><div className="ac-stack"><Panel title="Sign out"><h2 className="ac-display">Take care, <em>{session.name.split(" ")[0]}.</em></h2><p>You can sign out of this device. Your account and saved information will be here when you return.</p><form action={logoutCustomer}><button className="ac-button ac-signout"><LockKeyhole size={19}/>Sign out from this device</button></form><p className="ac-muted ac-spaced">Signing out from all devices is not available here yet.</p></Panel><Panel title="Current session"><div className="ac-session-state"><span className="ac-active-dot"/>Active now<span className="ac-badge">This session</span></div><div className="ac-value"><Monitor/><div><h3>{session.email}</h3><p>Signed in securely on this browser.</p></div></div></Panel><Panel title="Recent device logins"><Monitor className="ac-feature-icon"/><h3>Your sign-in history</h3><p>Device history and remote sign-out are not available in your account yet. If you’re concerned about access, reset your password or contact us.</p><ActionLink href={`/forgot-password?email=${encodeURIComponent(session.email)}`}>Reset password</ActionLink></Panel><Promo title="There’s always more to explore." body="New recipes, nourishing essentials and coconut goodness await you." action="Explore .CO" scene={5}/></div><div className="ac-stack"><Panel title="Your account"><ShieldCheck className="ac-feature-icon"/><h2 className="ac-display ac-display--small">Your peace of mind matters.</h2><p>Keep your account details current and use a password that’s unique to you.</p><div className="ac-value"><LockKeyhole/><p>Manage your password through secure email verification.</p></div><div className="ac-value"><Bell/><p>Contact support if something doesn’t look right.</p></div><ActionLink href="/contact" secondary>Account support</ActionLink></Panel><Promo title="Good things find their way back." body="Your favourites are ready whenever you return." action="Your wishlist" href="/wishlist" scene={5} className="ac-promo--tall"/></div></div>;}
