"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { Check, Package, Search, Truck } from "lucide-react";
import type { AccountData, AccountOrder } from "@/lib/account/data";
import type { CustomerSession } from "@/lib/customer/auth-config";
import { accountDate, accountMoney, orderStatusLabel, orderStep } from "@/lib/account/display";
import { ActionLink, EmptyCard, HelpPanel, Panel, Promo, Unavailable } from "./AccountShell";
import { ProductRail } from "./AccountCollections";
export function DeliveryTracker({status}:{status:string}) {const step=orderStep(status);return <ol className="ac-tracker" aria-label="Order progress">{["Order placed","Processing","Shipped","In transit","Delivered"].map((label,index)=><li key={label} className={index<=step?"is-reached":""} aria-current={index===step?"step":undefined}><span>{index<step?<Check size={18}/>:index===step?<Truck size={18}/>:<Package size={16}/>}</span><p>{label}</p></li>)}</ol>;}
export function OrderRow({order}:{order:AccountOrder}) {return <article className="ac-order-row"><div><time>{accountDate(order.placedAt)}</time><h3>Order #{order.orderId}</h3><p>{order.items?.length??0} items</p></div><div><span className={`ac-badge ${order.status==="DELIVERED"?"ac-badge--green":""}`}>{orderStatusLabel(order.status)}</span><p className="ac-price">{accountMoney(order.total,order.currency)}</p></div><ActionLink href={`/orders/${encodeURIComponent(order.orderId)}`}>View details</ActionLink></article>;}
export function Orders({data,session,history=false}:{data:AccountData;session:CustomerSession;history?:boolean}) {
 const [query,setQuery]=useState("");const [status,setStatus]=useState("all");const [year,setYear]=useState("all");const [sort,setSort]=useState("new");const [page,setPage]=useState(1);
 const filtered=useMemo(()=>data.orders.filter(o=>(status==="all"||o.status===status)&&(year==="all"||o.placedAt?.startsWith(year))&&`${o.orderId} ${o.items?.map(i=>i.name).join(" ")}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(sort==="new"?1:-1)*((Date.parse(b.placedAt||"")||0)-(Date.parse(a.placedAt||"")||0))),[data.orders,query,status,year,sort]);
 const current=data.orders.find(o=>!["DELIVERED","CANCELLED"].includes(o.status));const pages=Math.max(1,Math.ceil(filtered.length/6));
 return <><div className="ac-columns"><div className="ac-stack">{data.unavailable.orders&&<Unavailable>We couldn’t load your orders. Please refresh to try again.</Unavailable>}{!history&&<Panel title="Current order" action={current?<span className="ac-badge">{orderStatusLabel(current.status)}</span>:undefined}>{data.unavailable.orders?<Unavailable>Your current order status is unavailable.</Unavailable>:current?<><h2 className="ac-display">Good things are on their way.</h2><p>Order #{current.orderId}</p><DeliveryTracker status={current.status}/><ActionLink href={`/orders/${encodeURIComponent(current.orderId)}`}>View order details</ActionLink></>:<EmptyCard title="Your next coconut moment awaits." body="Once you place your first order, this is where its journey will appear." href="/shop" action="Explore our products" scene={3}/>}</Panel>}
 <Panel title={history?"Your orders":"Recent orders"} action={!history?<ActionLink href="/orders/history" secondary>View all orders</ActionLink>:undefined}>
 {history&&<div className="ac-filters"><label className="ac-search"><Search size={17}/><input aria-label="Search orders" placeholder="Product or order number" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label><select aria-label="Order year" value={year} onChange={e=>{setYear(e.target.value);setPage(1);}}><option value="all">All orders</option>{Array.from(new Set(data.orders.map(o=>o.placedAt?.slice(0,4)).filter(Boolean))).map(y=><option key={y}>{y}</option>)}</select><select aria-label="Order status" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="all">All status</option>{Array.from(new Set(data.orders.map(o=>o.status))).map(s=><option value={s} key={s}>{orderStatusLabel(s)}</option>)}</select><select aria-label="Order sort" value={sort} onChange={e=>{setSort(e.target.value);setPage(1);}}><option value="new">Newest first</option><option value="old">Oldest first</option></select></div>}
 {data.unavailable.orders?<Unavailable>Your order history is unavailable. No empty-account assumption has been made.</Unavailable>:filtered.length?<div className="ac-order-timeline">{filtered.slice((page-1)*6,page*6).map(o=><OrderRow order={o} key={o.orderId}/>)}</div>:data.orders.length?<div className="ac-no-results"><h3>No matching orders.</h3><button className="ac-button" onClick={()=>{setQuery("");setStatus("all");setYear("all");}}>Clear filters</button></div>:<div className="ac-no-results"><Package size={30}/><h3>No orders yet</h3><p>Your order history will appear here after your first order.</p><ActionLink href="/shop">Start exploring</ActionLink></div>}
 {pages>1&&<nav className="ac-pagination" aria-label="Order history pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} of {pages}</span><button disabled={page===pages} onClick={()=>setPage(p=>p+1)}>Next</button></nav>}
 </Panel></div><div className="ac-stack"><Panel><div className="ac-member-mini"><div className="ac-avatar">{session.initials}</div><div><p>Hello again,</p><h2>{data.profile?.displayName||session.name}</h2><ActionLink href="/profile" secondary>Edit profile</ActionLink></div></div><div className="ac-mini-stats"><Link href="/wishlist" aria-label={data.unavailable.saved?"Saved products currently unavailable":undefined}><strong>{data.unavailable.saved?"—":data.saved.productIds.length}</strong>Saved products{data.unavailable.saved&&<small>Currently unavailable</small>}</Link><Link href="/saved-recipes" aria-label={data.unavailable.saved?"Saved recipes currently unavailable":undefined}><strong>{data.unavailable.saved?"—":data.saved.recipeIds.length}</strong>Saved recipes{data.unavailable.saved&&<small>Currently unavailable</small>}</Link></div></Panel><HelpPanel/><Promo title="Recreate your ritual." body="Find the familiar favourites that make your day." action="Explore essentials" scene={5}/></div></div>
 <div className="ac-two-up"><Promo title="Running low?" body="Keep your favourites close, ready for your next visit." href="/wishlist" action="Your favourites" scene={1}/><Promo title="Complete your pantry." body="A little coconut goodness for everyday cooking." href="/shop?category=kitchen#all-products" action="Explore the kitchen" scene={7}/></div><ProductRail products={data.products.slice(0,6)} title="You might also like"/></>;
}
export function OrderDetail({data,order}:{data:AccountData;order:AccountOrder|null}) {return <><ActionLink href="/orders/history" secondary>Back to orders</ActionLink>{!order?<Panel title="Order details"><EmptyCard title="Order details aren’t available yet." body="We can’t display a receipt or delivery timeline for this order. Visit your order history or contact us for help." href="/orders/history" action="View order history" scene={3}/></Panel>:<><Panel><div className="ac-panel-heading"><h2 className="ac-display ac-display--small">Order #{order.orderId}</h2><span className="ac-badge">{orderStatusLabel(order.status)}</span></div><p>Ordered on {accountDate(order.placedAt)}</p></Panel><div className="ac-columns"><Panel title="Items in this order">{order.items?.map((item,index)=><div className="ac-line-item" key={`${item.productId}-${index}`}><div><h3>{item.name}</h3><p>Quantity {item.quantity}</p></div><strong>{accountMoney(item.price,order.currency)}</strong></div>)}</Panel><Panel title="Order summary"><h3>Total</h3><p className="ac-price">{accountMoney(order.total,order.currency)}</p><p>Payment and receipt information are not available for this order.</p></Panel></div><Panel title="Delivery tracker"><DeliveryTracker status={order.status}/><ActionLink href="/track-order">Tracking information</ActionLink></Panel></>}<div className="ac-two-up"><HelpPanel/><Promo title="More than products. A kinder tomorrow." body="Thank you for being part of the .CO journey." scene={5}/></div><ProductRail products={data.products.slice(0,6)} title="You might also like"/></>;}
