"use client";
import Link from "next/link";
import { useMemo, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, ChefHat, Clock, Heart, Search, ShoppingBag, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { ResponsiveImage } from "@/components/media/ResponsiveImage";
import { useCart } from "@/lib/cart/cart-context";
import type { ContentProduct, ContentRecipe } from "@/lib/content/types";
import type { SavedCard } from "@/components/auth/SavedContentGrid";
import { ActionLink, EmptyCard, Panel } from "./AccountShell";
export function ProductCard({product}:{product:ContentProduct}) {
 const cart=useCart();
 return <article className="ac-product"><Link href={`/shop?product=${product.slug}#all-products`} className="ac-product-image"><ResponsiveImage src={product.image} alt={product.name} fill sizes="(max-width:600px) 70vw, 240px" className="object-contain"/></Link><div className="ac-product-copy"><h3><Link href={`/shop?product=${product.slug}#all-products`}>{product.name}</Link></h3><p>{product.format}</p>{product.price!=null&&<span className="ac-price">₹{product.price.toLocaleString("en-IN")}</span>}<small className="ac-stock">{product.availabilityStatus === "in-stock" ? "In stock" : product.availabilityStatus === "out-of-stock" ? "Out of stock" : "Product preview"}</small><button className="ac-button" disabled={product.availabilityStatus==="out-of-stock"} onClick={()=>cart.addItem(product.slug)}><span>Add to cart</span><ArrowRight size={15}/></button></div></article>;
}
export function ProductRail({products,title="A little more .CO"}:{products:ContentProduct[];title?:string}) {
 const rail=useRef<HTMLDivElement>(null);
 const move=(direction:number)=>rail.current?.scrollBy({left:direction*(rail.current.clientWidth*.8),behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
 return <Panel title={title} className="ac-rail-panel" action={<div className="ac-rail-controls"><button aria-label={`Previous ${title}`} onClick={()=>move(-1)}><ArrowLeft size={18}/></button><button aria-label={`Next ${title}`} onClick={()=>move(1)}><ArrowRight size={18}/></button></div>}><div className="ac-rail" ref={rail}>{products.map(p=><ProductCard key={p.slug} product={p}/>)}</div></Panel>;
}
export function RecipeCard({recipe}:{recipe:ContentRecipe}) {return <article className="ac-recipe"><Link className="ac-recipe-image" href={`/recipes/${recipe.slug}`}><ResponsiveImage src={recipe.image} alt={recipe.title} fill sizes="(max-width:600px) 85vw, 350px" className="object-cover"/></Link><div className="ac-recipe-copy"><h3>{recipe.title}</h3><p>{recipe.description}</p><div className="ac-recipe-meta"><span><Clock size={15}/>{recipe.time}</span><span><ChefHat size={15}/>{recipe.difficulty}</span></div><ActionLink href={`/recipes/${recipe.slug}`}>Cook this</ActionLink></div></article>;}
export function SavedCollection({items:initialItems,recipes=false}:{items:SavedCard[];recipes?:boolean}) {
 const router=useRouter();const cart=useCart();const [items,setItems]=useState(initialItems);const [query,setQuery]=useState("");const [sort,setSort]=useState("recent");const [kind,setKind]=useState("all");const [pending,setPending]=useState<string[]>([]);const [message,setMessage]=useState("");
 const visible=useMemo(()=>{const selected=items.filter(x=>(kind==="all"||x.kind===kind)&&`${x.title} ${x.detail}`.toLowerCase().includes(query.toLowerCase()));return sort==="name"?selected.sort((a,b)=>a.title.localeCompare(b.title)):selected;},[items,query,sort,kind]);
 async function remove(item:SavedCard){const key=`${item.kind}:${item.id}`;if(pending.includes(key))return;setPending(v=>[...v,key]);setMessage("");const response=await fetch("/api/customer/saved",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({kind:item.kind,itemId:item.id})}).catch(()=>null);if(response?.ok){setItems(v=>v.filter(x=>x.id!==item.id||x.kind!==item.kind));setMessage(`${item.title} removed.`);router.refresh();}else setMessage("We couldn’t remove that item. Please try again.");setPending(v=>v.filter(x=>x!==key));}
 return <Panel title={recipes?"Your saved recipes":"Your saved collection"} action={<span className="ac-count">{items.length}</span>}>
  <div className="ac-filters"><label className="ac-search"><Search size={17}/><input aria-label="Search saved items" placeholder="Search your favourites" value={query} onChange={e=>setQuery(e.target.value)}/></label>{!recipes&&<select aria-label="Saved item type" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">All saved</option><option value="product">Products</option><option value="recipe">Recipes</option><option value="journal">Stories</option><option value="community">Community</option><option value="recent">Recently viewed</option></select>}<select aria-label="Sort saved items" value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">Saved order</option><option value="name">Name A–Z</option></select></div>
  <p role="status" className="ac-feedback">{message}</p>
  {visible.length?<div className={`ac-saved-grid ${recipes?"ac-saved-grid--recipes":""}`}>{visible.map(item=><article className="ac-saved-card" key={`${item.kind}:${item.id}`}><Link href={item.href} className={`ac-saved-image ${item.cartSlug?"ac-saved-image--product":""}`}><ResponsiveImage src={item.image} alt={item.title} fill sizes="(max-width:600px) 85vw, 300px" className={item.cartSlug?"object-contain":"object-cover"}/></Link><button className="ac-save-heart" disabled={pending.includes(`${item.kind}:${item.id}`)} aria-label={`Remove ${item.title}`} onClick={()=>void remove(item)}>{pending.includes(`${item.kind}:${item.id}`)?<Trash2 size={19}/>:<Heart size={20} fill="currentColor"/>}</button><div className="ac-saved-copy"><small>{item.kind==="recent"?"Recently viewed":item.kind}</small><h3><Link href={item.href}>{item.title}</Link></h3><p>{item.detail}</p>{item.cartSlug?<button className="ac-button" onClick={()=>cart.addItem(item.cartSlug!)}><ShoppingBag size={16}/>Add to cart<ArrowRight size={16}/></button>:<ActionLink href={item.href}>{item.kind==="recipe"?"Cook this":"Continue reading"}</ActionLink>}<ActionLink href={item.href} secondary>{item.kind==="recipe"?"View recipe":"View details"}</ActionLink></div></article>)}</div>:query||kind!=="all"?<div className="ac-no-results"><h3>No matches yet.</h3><p>Try a different search or show all saved items.</p><button className="ac-button" onClick={()=>{setQuery("");setKind("all");}}>Clear filters</button></div>:<EmptyCard title={recipes?"No saved recipes yet":"Your wishlist is empty"} body={recipes?"Discover delicious coconut-inspired recipes and save your favourites.":"Save the products and stories you love, so they’re always within reach."} href={recipes?"/recipes":"/shop"} action={recipes?"Explore recipes":"Start exploring"} scene={recipes?7:5}/>}
 </Panel>;
}
