"use client";

import Image from "next/image";
import Link from "next/link";
import { AnimatePresence, motion, useMotionValue, useReducedMotion } from "framer-motion";
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, Bookmark, Camera, Check, Droplets, Heart, Instagram, Leaf, Menu, MessageCircle, PackageOpen, Play, Recycle, Search, Sparkles, Star, Trash2, UserRound, X, Youtube } from "lucide-react";
import { MobileBottomNav, NewsletterSection, ReferenceFooter, ReferenceHeader } from "@/components/home/ReferenceHomePage";
import { communityPosts, communityTestimonials as testimonials, journalArticles as articles, routineCards } from "@/data/journal";
import { cn } from "@/lib/utils";

const blur="data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIHdpZHRoPSc0MCcgaGVpZ2h0PSc0MCc+PHJlY3Qgd2lkdGg9JzEwMCUnIGhlaWdodD0nMTAwJScgZmlsbD0nI2Y4ZjRlYycvPjwvc3ZnPg==";
const ease=[.16,1,.3,1] as const;

function PremiumImage({src,alt,sizes,className="",priority=false}:{src:string;alt:string;sizes:string;className?:string;priority?:boolean}){return <Image src={src} alt={alt} fill sizes={sizes} priority={priority} quality={95} placeholder="blur" blurDataURL={blur} className={cn("object-cover transition duration-700 group-hover:scale-[1.035]",className)}/>;}
function ArrowButton({label,onClick}:{label:string;onClick?:()=>void}){return <button type="button" onClick={onClick} aria-label={label} className="grid size-11 place-items-center rounded-full border border-[#214d2b]/25 bg-white/70 transition hover:bg-[#214d2b] hover:text-white"><ArrowRight size={16}/></button>;}

export function ReferenceJournalPage(){
  const reduce=useReducedMotion();
  const railRef=useRef<HTMLDivElement>(null);
  const [post,setPost]=useState<(typeof communityPosts)[number]|null>(null);
  const [deck,setDeck]=useState(()=>[...communityPosts.slice(0,5)]);
  const [toast,setToast]=useState("");
  const [creator,setCreator]=useState(false);
  const [category,setCategory]=useState("All");
  useEffect(()=>{if(reduce)return;const node=railRef.current;if(!node)return;const timer=window.setInterval(()=>{if(node.matches(":hover"))return;node.scrollBy({left:1,behavior:"auto"});if(node.scrollLeft>node.scrollWidth/2)node.scrollLeft=0;},32);return()=>clearInterval(timer);},[reduce]);
  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==="Escape"){setPost(null);setCreator(false);}};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close);},[]);
  const swipe=(action:"like"|"save"|"skip")=>{if(!deck.length)return;const current=deck[0];setDeck((items)=>[...items.slice(1),items[0]]);if(action==="save")setToast("Pinned to your routine");else if(action==="like")setToast(`Loved ${current.handle}`);else setToast("Next story");window.setTimeout(()=>setToast(""),1800);};
  const filtered=category==="All"?articles:articles.filter(([item])=>item===category);
  return <div className="min-h-screen overflow-hidden bg-[#f8f4ec] font-['Inter'] text-[#2a1b13]">
    <ReferenceHeader/>
    <main>
      <section className="relative min-h-[520px] overflow-hidden bg-[#f3eee4] md:min-h-[510px]"><div className="absolute inset-y-0 right-0 hidden w-[61%] md:block"><PremiumImage src="/assets/journal/refined/community-coconut-table.png" alt="The .CO community sharing coconut rituals around a sunlit table" sizes="61vw" priority/><div className="absolute inset-0 bg-gradient-to-r from-[#f3eee4] via-[#f3eee4]/20 to-transparent"/></div><div className="absolute right-[-70px] top-28 h-[360px] w-[260px] md:hidden"><PremiumImage src="/assets/home/refined/naturally-hydrating-4k.png" alt=".CO coconut water and fresh coconut" sizes="260px" priority className="object-[65%_center]"/></div><div className="absolute inset-0 bg-gradient-to-r from-[#f8f4ec] via-[#f8f4ec]/90 to-transparent md:w-[62%]"/><div className="relative mx-auto flex min-h-[520px] max-w-[1500px] items-center px-5 py-14 md:min-h-[510px] md:px-[clamp(48px,6vw,92px)]"><motion.div initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.8,ease}} className="max-w-[470px]"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[#214d2b]">The .CO Journal</p><h1 className="mt-5 font-['Cormorant_Garamond'] text-[57px] leading-[.9] tracking-[-.035em] md:text-[74px]">Real people.<br/>Real stories.<br/><em className="font-normal text-[#214d2b]">Real impact.</em></h1><p className="mt-6 max-w-[31ch] text-sm leading-7 text-[#5f554d]">A space for our community to share ideas, recipes, rituals, and real-life moments with .CO.</p><a href="#share" className="mt-7 inline-flex min-h-12 items-center gap-4 rounded-full bg-[#214d2b] px-6 text-[10px] font-semibold uppercase text-white">Share your story <ArrowRight size={15}/></a></motion.div></div></section>

      <section className="px-4 py-14 md:px-8"><div className="mx-auto max-w-[1400px]"><SectionTitle index="01" label="Live from our community" title="What’s happening right now" action="View all posts"/><div ref={railRef} className="mt-6 flex snap-x gap-3 overflow-x-auto pb-3 [scrollbar-width:none]">{[...communityPosts,...communityPosts].map((item,index)=><button type="button" key={`${item.handle}-${index}`} onClick={()=>setPost(item)} className="group min-w-[225px] snap-start overflow-hidden rounded-[22px] border border-black/6 bg-white/56 text-left shadow-[0_12px_35px_rgba(42,27,19,.045)] md:min-w-[240px]"><div className="flex items-center gap-2 p-3"><span className="grid size-7 place-items-center rounded-full bg-[#dfe7d9]"><Leaf size={12}/></span><span><b className="block text-[9px]">{item.handle}</b><small className="text-[8px] text-black/45">{item.time}</small></span></div><div className="relative aspect-square overflow-hidden"><PremiumImage src={item.image} alt={item.caption} sizes="240px"/></div><div className="flex min-h-[76px] items-start justify-between gap-2 p-3"><p className="text-[10px] leading-5">{item.caption}</p><span className="flex items-center gap-1 text-[9px] text-[#a34e48]"><Heart size={13}/>{item.likes}</span></div></button>)}</div></div></section>

      <section className="bg-white/28 px-4 py-14 md:px-8"><div className="mx-auto max-w-[1400px]"><SectionTitle index="02" label="Husk swiper" title="Swipe. Discover. Get inspired." description="Real reviews, recipes & unboxings from our amazing community."/><div className="mt-8 grid gap-8 md:grid-cols-[310px_1fr] md:items-center"><div className="md:pr-6"><p className="font-['Cormorant_Garamond'] text-3xl leading-tight">Real community stories, one joyful swipe at a time.</p><p className="mt-4 text-xs leading-6 text-[#665c54]">Like the moments you love. Save useful rituals to your routine. Skip anything that is not for you.</p><div className="mt-7 flex gap-3"><SwipeControl label="Like" icon={Heart} onClick={()=>swipe("like")}/><SwipeControl label="Save" icon={Bookmark} onClick={()=>swipe("save")}/><SwipeControl label="Skip" icon={X} onClick={()=>swipe("skip")}/></div><p className="mt-4 text-center text-[8px] uppercase tracking-[.18em] text-black/45 md:text-left">Drag to swipe</p></div><div className="relative min-h-[470px] md:min-h-[500px]">{deck.slice(0,5).map((item,index)=><SwipeCard key={item.handle} item={item} index={index} onSwipe={swipe}/>)}</div></div></div></section>

      <section className="px-4 py-16 md:px-8"><div className="mx-auto grid max-w-[1400px] gap-6 md:grid-cols-[.62fr_1.38fr]"><div><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#214d2b]">03 &nbsp; Community co-creation workspace</p><h2 className="mt-3 font-['Cormorant_Garamond'] text-[43px] leading-[.94]">Build your day.<br/>Powered by our community.</h2><p className="mt-4 max-w-[40ch] text-xs leading-6 text-[#655b53]">Drag, drop or tap real community posts into your routine. Get your Organic Synergy Score, Daily Hydration Index, and Plastic Avoided — in real time.</p><Link href="/journal/social-cocreation-hub" className="mt-6 inline-flex min-h-11 items-center gap-4 rounded-full bg-[#214d2b] px-5 text-[9px] font-semibold uppercase text-white">Open the hub <ArrowRight size={13}/></Link><div className="mt-7 grid grid-cols-3 gap-2">{[["87%","Organic Synergy",Leaf],["92%","Daily Hydration",Droplets],["12","Plastic Avoided",Recycle]].map(([value,label,Icon])=>{const I=Icon as typeof Leaf;return <div key={String(label)} className="rounded-[17px] border border-black/6 bg-white/52 p-3"><b className="font-['Cormorant_Garamond'] text-2xl">{String(value)}</b><span className="mt-1 block text-[7px] leading-3">{String(label)}</span><I size={16} className="mt-3 text-[#214d2b]"/></div>})}</div></div><RoutinePreview onCreator={()=>setCreator(true)}/></div></section>

      <section className="bg-white/28 px-4 py-14 md:px-8"><div className="mx-auto max-w-[1400px]"><SectionTitle index="04" label="Stories, ideas & more" title="Dive deeper into what matters" action="View all articles"/><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{filtered.map(([type,title,time,image])=><Link href={`/journal?category=${encodeURIComponent(type)}`} key={title} className="group"><div className="relative aspect-[4/3] overflow-hidden rounded-[19px]"><PremiumImage src={image} alt={title} sizes="(min-width:1024px) 19vw, 46vw"/></div><p className="mt-3 text-[8px] font-semibold uppercase tracking-[.12em] text-[#214d2b]">{type}</p><h3 className="mt-2 font-['Cormorant_Garamond'] text-[22px] leading-[1.05]">{title}</h3><p className="mt-2 text-[8px] text-black/48">{time}</p></Link>)}</div></div></section>

      <section className="px-4 py-16 md:px-8"><div className="mx-auto grid max-w-[1400px] gap-5 lg:grid-cols-[1fr_.72fr]"><div><h2 className="font-['Cormorant_Garamond'] text-[43px]">Community Love</h2><p className="text-xs text-[#685e55]">Real words from real people</p><div className="mt-6 flex snap-x gap-3 overflow-x-auto pb-2 [scrollbar-width:none]">{testimonials.map(([name,quote,avatar])=><article key={name} className="min-w-[285px] snap-start rounded-[24px] border border-black/6 bg-white/55 p-6 md:min-w-[320px]"><div className="flex text-[#e4a400]">{Array.from({length:5}).map((_,i)=><Star key={i} size={13} fill="currentColor"/>)}</div><p className="mt-5 font-['Cormorant_Garamond'] text-xl leading-8">“{quote}”</p><div className="mt-5 flex items-center gap-3"><span className="relative size-10 overflow-hidden rounded-full"><PremiumImage src={avatar} alt={name} sizes="40px"/></span><span><b className="block text-[9px]">{name}</b><small className="text-[8px] text-black/45">Verified Buyer</small></span></div></article>)}</div></div><aside className="space-y-5"><div><h3 className="font-['Cormorant_Garamond'] text-3xl">Journal Categories</h3><div className="mt-4 overflow-hidden rounded-[22px] border border-black/6 bg-white/46">{[["Recipes","Delicious & healthy",Sparkles],["Sustainability","Tips, ideas & impact",Leaf],["Community","Stories & spotlights",Heart],["Wellness","Rituals & self-care",Droplets],["Behind .CO","Our journey",PackageOpen]].map(([name,desc,Icon])=>{const I=Icon as typeof Leaf;return <button type="button" key={String(name)} onClick={()=>setCategory(name===category?"All":String(name))} className={cn("flex w-full items-center gap-3 border-b border-black/6 p-4 text-left last:border-0",category===name&&"bg-[#e8eee2]")}><span className="grid size-10 place-items-center rounded-full border border-[#214d2b]/18"><I size={17}/></span><span className="flex-1"><b className="block text-[10px]">{String(name)}</b><small className="text-[8px] text-black/46">{String(desc)}</small></span><ArrowRight size={14}/></button>})}</div></div><div id="share" className="rounded-[22px] border border-black/6 bg-[#f3eee4] p-6"><h3 className="font-['Cormorant_Garamond'] text-3xl">Join the Conversation</h3><p className="mt-2 text-xs leading-5">Follow us & be part of our growing community.</p><div className="mt-5 flex gap-3">{[Instagram,Play,Youtube,Camera].map((Icon,index)=><a href={index===0?"https://www.instagram.com/cothecoconutcompany":"#share"} aria-label={["Instagram","TikTok","YouTube","Pinterest"][index]} key={index} className="grid size-10 place-items-center rounded-full border border-black/7 bg-white/60"><Icon size={17}/></a>)}</div></div></aside></div></section>
      <NewsletterSection/>
    </main><ReferenceFooter/><MobileBottomNav/>
    <AnimatePresence>{post&&<PostModal post={post} close={()=>setPost(null)}/>} {creator&&<CreatorModal close={()=>setCreator(false)}/>} {toast&&<motion.div initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} exit={{opacity:0,y:18}} className="fixed bottom-24 left-1/2 z-[190] -translate-x-1/2 rounded-full bg-[#214d2b] px-5 py-3 text-[10px] font-semibold text-white shadow-2xl"><Check className="mr-2 inline" size={14}/>{toast}</motion.div>}</AnimatePresence>
  </div>;
}

function SectionTitle({index,label,title,description,action}:{index:string;label:string;title:string;description?:string;action?:string}){return <div className="flex items-end justify-between gap-4"><div><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#214d2b]">{index} &nbsp; {label}</p><h2 className="mt-3 font-['Cormorant_Garamond'] text-[40px] leading-none md:text-[46px]">{title}</h2>{description&&<p className="mt-3 text-xs text-[#655b53]">{description}</p>}</div>{action&&<span className="hidden rounded-full border border-[#214d2b]/25 px-5 py-3 text-[8px] font-semibold uppercase md:block">{action}</span>}</div>}
function SwipeControl({label,icon:Icon,onClick}:{label:string;icon:typeof Heart;onClick:()=>void}){return <button type="button" onClick={onClick} aria-label={label} className="grid size-12 place-items-center rounded-full border border-black/7 bg-white shadow-[0_8px_22px_rgba(42,27,19,.1)] transition hover:-translate-y-1 hover:bg-[#214d2b] hover:text-white"><Icon size={18}/></button>}
function SwipeCard({item,index,onSwipe}:{item:(typeof communityPosts)[number];index:number;onSwipe:(action:"like"|"save"|"skip")=>void}){const x=useMotionValue(0);return <motion.article drag={index===0?"x":false} style={{x,zIndex:10-index,rotate:index===0?0:(index-2)*3,y:index*7}} dragConstraints={{left:-180,right:180}} onDragEnd={(_,info)=>{if(info.offset.x>100)onSwipe("like");else if(info.offset.x< -100)onSwipe("skip");}} className="absolute left-1/2 top-0 w-[270px] -translate-x-1/2 cursor-grab overflow-hidden rounded-[24px] border-[8px] border-white bg-white shadow-[0_22px_60px_rgba(42,27,19,.15)] md:w-[330px]"><div className="relative aspect-[4/3]"><PremiumImage src={item.image} alt={item.caption} sizes="330px"/></div><div className="p-5"><div className="flex items-center justify-between"><b className="text-[9px]">{item.handle}</b><span className="rounded-full bg-[#eee9de] px-2 py-1 text-[7px]">{item.category}</span></div><div className="mt-3 flex text-[#e4a400]">{Array.from({length:5}).map((_,i)=><Star key={i} size={12} fill="currentColor"/>)}</div><p className="mt-3 text-xs leading-6">{item.caption}. A small ritual that makes the day feel better.</p><div className="mt-4 flex gap-4 text-[8px] text-black/48"><span><Heart className="mr-1 inline" size={12}/>{item.likes}</span><span><MessageCircle className="mr-1 inline" size={12}/>{Math.floor(item.likes/6)}</span></div></div></motion.article>}
function RoutinePreview({onCreator}:{onCreator:()=>void}){return <div className="rounded-[27px] border border-black/7 bg-white/62 p-4 shadow-[0_18px_48px_rgba(42,27,19,.07)]"><div className="flex items-center justify-between border-b border-black/6 pb-4"><b className="font-['Cormorant_Garamond'] text-2xl">Your Day Routine Canvas</b><button onClick={onCreator} type="button" className="text-[8px] font-semibold uppercase text-[#214d2b]">Trending creators</button></div><div className="mt-4 grid grid-cols-3 gap-2">{["Morning","Afternoon","Night"].map((period)=><div key={period}><p className="mb-3 text-center text-[8px] font-semibold uppercase">{period}</p>{routineCards.filter((card)=>card.period===period.toLowerCase()).slice(0,1).map((card)=><button type="button" onClick={onCreator} key={card.id} className="w-full overflow-hidden rounded-[15px] border border-black/6 bg-[#f8f4ec] text-left"><div className="relative aspect-[4/3]"><PremiumImage src={card.image} alt={card.title} sizes="230px"/></div><div className="p-2"><span className="block text-[7px] text-black/42">{card.handle}</span><b className="text-[8px]">{card.title}</b></div></button>)}<div className="mt-2 grid h-16 place-items-center rounded-[13px] border border-dashed border-black/15 text-xl text-[#214d2b]">+</div></div>)}</div></div>}
function PostModal({post,close}:{post:(typeof communityPosts)[number];close:()=>void}){return <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={close} className="fixed inset-0 z-[180] grid place-items-center bg-[#1e1510]/65 p-4 backdrop-blur-sm"><motion.article initial={{scale:.94,y:18}} animate={{scale:1,y:0}} exit={{scale:.94,y:18}} onClick={(e)=>e.stopPropagation()} className="w-full max-w-[720px] overflow-hidden rounded-[28px] bg-[#f8f4ec] md:grid md:grid-cols-2"><div className="relative min-h-[340px]"><PremiumImage src={post.image} alt={post.caption} sizes="(min-width:768px) 360px, 92vw"/></div><div className="relative p-6"><button onClick={close} className="absolute right-4 top-4 grid size-10 place-items-center rounded-full bg-white" aria-label="Close post"><X size={16}/></button><p className="text-[9px] font-semibold text-[#214d2b]">{post.handle}</p><h3 className="mt-8 font-['Cormorant_Garamond'] text-4xl">{post.caption}</h3><p className="mt-5 text-xs leading-6 text-[#655b53]">A real moment shared by our community—simple, useful and made to be passed along.</p><div className="mt-7 flex gap-3"><button className="rounded-full bg-[#214d2b] px-5 py-3 text-[9px] font-semibold uppercase text-white">Love this</button><button className="grid size-10 place-items-center rounded-full border border-black/10"><Bookmark size={15}/></button></div></div></motion.article></motion.div>}
function CreatorModal({close}:{close:()=>void}){return <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={close} className="fixed inset-0 z-[180] grid place-items-center bg-[#1e1510]/65 p-4 backdrop-blur-sm"><motion.div initial={{scale:.94,y:18}} animate={{scale:1,y:0}} exit={{scale:.94,y:18}} onClick={(e)=>e.stopPropagation()} className="relative w-full max-w-[700px] rounded-[28px] bg-[#f8f4ec] p-6 md:p-8"><button onClick={close} className="absolute right-4 top-4 grid size-10 place-items-center rounded-full bg-white" aria-label="Close creator spotlight"><X size={16}/></button><div className="flex items-center gap-4"><span className="relative size-16 overflow-hidden rounded-full"><PremiumImage src="/assets/social/afsala-founder-clean.png" alt="Botanical Bess" sizes="64px"/></span><div><h3 className="font-['Cormorant_Garamond'] text-3xl">@botanical_bess</h3><p className="text-[9px] text-[#214d2b]">Eco Lifestyle Creator</p></div></div><div className="mt-7 grid grid-cols-3 gap-2">{[["12.4k","Followers"],["387","Posts"],["98%","Sustainability"]].map(([value,label])=><div key={label} className="rounded-[16px] bg-white/65 p-4"><b className="font-['Cormorant_Garamond'] text-2xl">{value}</b><span className="block text-[8px]">{label}</span></div>)}</div><blockquote className="mt-6 font-['Cormorant_Garamond'] text-2xl leading-8">“I’ve switched to .CO because it aligns with my values — clean ingredients, real impact, zero compromise.”</blockquote><div className="mt-6 flex gap-3"><button className="rounded-full bg-[#214d2b] px-5 py-3 text-[9px] font-semibold uppercase text-white">View spotlight</button><Link href="/shop" className="rounded-full border border-[#214d2b]/30 px-5 py-3 text-[9px] font-semibold uppercase">Shop products</Link></div></motion.div></motion.div>}
