"use client";

import Image from "next/image";
import Link from "next/link";
import { AnimatePresence, motion } from "framer-motion";
import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, ChevronDown, ChefHat, Clock3, Cookie, CupSoda, Dumbbell, Heart, Leaf, Play, Search, ShieldCheck, ShoppingBag, Sparkles, Timer, Truck, UtensilsCrossed, WheatOff } from "lucide-react";
import { MobileBottomNav, NewsletterSection, ReferenceFooter, ReferenceHeader } from "@/components/home/ReferenceHomePage";
import { cn } from "@/lib/utils";
import { recipeCategories, recipes, type RecipeItem } from "./recipe-data";

const blurDataURL = "data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy5vcmcvMjAwMC9zdmcnIHdpZHRoPSc0MCcgaGVpZ2h0PSc0MCc+PHJlY3Qgd2lkdGg9JzEwMCUnIGhlaWdodD0nMTAwJScgZmlsbD0nI2YzZWVlNCcvPjwvc3ZnPg==";
const ease = [0.16, 1, 0.3, 1] as const;
const categoryIcons = [Sparkles, CupSoda, ChefHat, UtensilsCrossed, Cookie, CupSoda, Cookie, ChefHat, Leaf, WheatOff];

function PremiumImage({ src, alt, sizes, priority = false, className = "" }: { src: string; alt: string; sizes: string; priority?: boolean; className?: string }) {
  return <Image src={src} alt={alt} fill priority={priority} sizes={sizes} quality={95} placeholder="blur" blurDataURL={blurDataURL} className={cn("object-cover transition duration-700 group-hover:scale-[1.04]", className)} />;
}

export function ReferenceRecipesPage() {
  const [category, setCategory] = useState("All Recipes");
  const [search, setSearch] = useState("");
  const [searchOpen, setSearchOpen] = useState(false);
  const [saved, setSaved] = useState(new Set<string>());
  const [reviewIndex, setReviewIndex] = useState(0);
  const [featuredIndex, setFeaturedIndex] = useState(0);
  const featured = recipes[featuredIndex % recipes.length];
  const visible = useMemo(() => recipes.filter((recipe) => {
    const categoryMatch = category === "All Recipes" || category === "Smoothies" ? category === "All Recipes" || recipe.title.toLowerCase().includes("smoothie") : category === "Vegan" || category === "Gluten Free" ? true : recipe.category === category;
    const query = search.trim().toLowerCase();
    return categoryMatch && (!query || `${recipe.title} ${recipe.category} ${recipe.ingredients.join(" ")}`.toLowerCase().includes(query));
  }), [category, search]);
  const toggleSaved = (slug: string) => setSaved((current) => { const next = new Set(current); if (next.has(slug)) next.delete(slug); else next.add(slug); return next; });

  return (
    <div className="min-h-screen overflow-hidden bg-[#f8f4ec] font-['Inter'] text-[#2a1b13]">
      <ReferenceHeader />
      <main>
        <section className="relative min-h-[590px] overflow-hidden bg-[#f3eee4] md:min-h-[600px]">
          <PremiumImage src="/assets/recipes/refined/recipes-hero-editorial.png" alt=".CO coconut products with a mango coconut breakfast bowl" sizes="100vw" priority className="object-[70%_center] md:object-center" />
          <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(248,244,236,.99)_0%,rgba(248,244,236,.92)_37%,rgba(248,244,236,.18)_62%,rgba(248,244,236,0)_100%)] md:bg-[linear-gradient(90deg,rgba(248,244,236,.98)_0%,rgba(248,244,236,.88)_36%,rgba(248,244,236,.02)_67%)]" />
          <div className="relative mx-auto flex min-h-[590px] max-w-[1500px] items-center px-5 py-12 md:min-h-[600px] md:px-[clamp(48px,6vw,92px)]">
            <div className="max-w-[500px]"><p className="text-[10px] font-semibold uppercase tracking-[.15em] text-[#214d2b]">Recipes</p><h1 className="mt-5 font-['Cormorant_Garamond'] text-[52px] leading-[.88] tracking-[-.04em] md:text-[76px]">Good food.<br />Good for you.<br />Good for the <em className="font-normal text-[#214d2b]">planet.</em></h1><p className="mt-6 max-w-[330px] text-sm leading-7 text-[#5d5148]">Discover delicious, easy and wholesome recipes made with real coconut goodness.</p><div className="mt-7 flex flex-wrap gap-3"><a href="#featured-recipes" className="inline-flex min-h-12 items-center gap-4 rounded-full bg-[#214d2b] px-6 text-[10px] font-semibold uppercase text-white">Browse recipes <ArrowRight size={15}/></a><Link href="#featured-recipes" className="inline-flex min-h-12 items-center gap-2 rounded-full px-3 text-[10px] font-semibold uppercase"><span className="grid size-8 place-items-center rounded-full border border-[#214d2b]/40"><Play size={13}/></span> Watch video</Link></div></div>
          </div>
          <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.4,duration:.7,ease}} className="absolute bottom-10 right-[4vw] hidden w-[205px] rounded-[24px] border border-white/70 bg-white/72 p-4 shadow-[0_22px_65px_rgba(42,27,19,.14)] backdrop-blur-xl lg:block"><div className="flex items-center justify-between text-[9px] font-semibold">Recipe of the Day <Heart size={14}/></div><div className="relative mt-3 aspect-[4/3] overflow-hidden rounded-[15px]"><PremiumImage src="/assets/recipes/generated/co-green-coconut-smoothie-editorial-4k.avif" alt="Green coconut detox smoothie" sizes="205px" /></div><p className="mt-3 text-[11px] font-semibold">Green Coconut Detox Smoothie</p><p className="mt-2 flex gap-3 text-[8px] text-[#6e635b]"><span>◷ 5 min</span><span>Easy</span></p><Link href="/recipes/green-coconut-detox-smoothie" className="mt-3 inline-flex items-center gap-2 text-[9px] font-semibold uppercase">View recipe <ArrowRight size={12}/></Link></motion.div>
        </section>

        <section className="relative z-10 -mt-5 px-3 md:-mt-7 md:px-8"><div className="mx-auto flex max-w-[1320px] items-center gap-2 overflow-x-auto rounded-[25px] border border-white/70 bg-white/72 p-3 shadow-[0_18px_55px_rgba(42,27,19,.09)] backdrop-blur-xl [scrollbar-width:none] md:gap-1">{recipeCategories.map((item,index)=>{const Icon=categoryIcons[index];return <button type="button" key={item} onClick={()=>setCategory(item)} className={cn("group flex min-w-[78px] shrink-0 flex-col items-center gap-2 rounded-[16px] px-3 py-3 text-[8px] font-semibold",category===item&&"bg-[#f3eee4] text-[#214d2b]")}><Icon size={19} strokeWidth={1.5}/><span>{item}</span><span className={cn("h-0.5 w-0 bg-[#214d2b] transition-all",category===item&&"w-7")}/></button>})}<Link href="#community" className="ml-auto hidden min-h-[64px] min-w-[170px] items-center justify-between rounded-[17px] bg-[#214d2b] px-5 text-[10px] font-semibold text-white lg:flex"><span>Have a recipe to share?<br/><u>Submit Your Recipe</u></span><ArrowRight size={14}/></Link></div></section>

        <section className="px-4 py-16 md:px-8 md:py-20"><div className="mx-auto grid max-w-[1320px] gap-5 md:grid-cols-[.72fr_1.2fr_.68fr]"><div className="flex flex-col justify-center"><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#214d2b]">Recipe of the day</p><h2 className="mt-4 font-['Cormorant_Garamond'] text-[42px] leading-[.95] md:text-[48px]">{featured.title}</h2><p className="mt-5 text-xs leading-6 text-[#61564d]">{featured.description}</p><div className="mt-6 flex flex-wrap gap-4 text-[9px]"><span className="inline-flex items-center gap-2"><Clock3 size={14}/>{featured.time} min</span><span className="inline-flex items-center gap-2"><Timer size={14}/>{featured.difficulty}</span><span className="inline-flex items-center gap-2"><UtensilsCrossed size={14}/>2 servings</span></div><Link href={`/recipes/${featured.slug}`} className="mt-7 inline-flex min-h-12 w-fit items-center gap-4 rounded-full bg-[#214d2b] px-6 text-[9px] font-semibold uppercase text-white">View full recipe <ArrowRight size={14}/></Link></div><div className="group relative min-h-[470px] overflow-hidden rounded-[28px] md:min-h-[540px]"><PremiumImage src={featured.image} alt={featured.title} sizes="(min-width:768px) 45vw, 92vw" /><button type="button" onClick={()=>toggleSaved(featured.slug)} aria-label="Save featured recipe" className="absolute right-4 top-4 grid size-10 place-items-center rounded-full bg-white/80 backdrop-blur"><Heart size={17} fill={saved.has(featured.slug)?"currentColor":"none"}/></button><div className="absolute bottom-4 right-4 flex gap-2"><button type="button" aria-label="Previous recipe" onClick={()=>setFeaturedIndex((value)=>(value-1+recipes.length)%recipes.length)} className="grid size-10 place-items-center rounded-full bg-white/85"><ArrowLeft size={15}/></button><button type="button" aria-label="Next recipe" onClick={()=>setFeaturedIndex((value)=>(value+1)%recipes.length)} className="grid size-10 place-items-center rounded-full bg-white/85"><ArrowRight size={15}/></button></div></div><div className="grid gap-4"><ProductsUsed products={featured.products}/><DietaryVersions items={featured.variations}/></div></div></section>

        <section id="featured-recipes" className="px-4 pb-16 md:px-8"><div className="mx-auto max-w-[1320px]"><div className="flex items-end justify-between"><div><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#214d2b]">Featured recipes</p><h2 className="mt-3 font-['Cormorant_Garamond'] text-[38px] leading-none md:text-[46px]">Curated favourites for every moment.</h2></div><button type="button" onClick={()=>setSearchOpen((value)=>!value)} className="grid size-11 place-items-center rounded-full border border-black/8"><Search size={17}/></button></div><AnimatePresence>{searchOpen&&<motion.div initial={{opacity:0,height:0}} animate={{opacity:1,height:"auto"}} exit={{opacity:0,height:0}} className="overflow-hidden"><div className="mt-5 flex items-center rounded-full border border-black/8 bg-white/60 px-5"><Search size={16}/><input autoFocus value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Search by recipe, ingredient or meal type" className="h-12 flex-1 bg-transparent px-3 text-xs outline-none"/></div></motion.div>}</AnimatePresence><motion.div layout className="mt-7 grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-6">{visible.map((recipe,index)=><RecipeCard key={recipe.slug} recipe={recipe} index={index} saved={saved.has(recipe.slug)} onSave={()=>toggleSaved(recipe.slug)}/>)}</motion.div>{!visible.length&&<div className="mt-6 rounded-[28px] bg-white/55 px-6 py-16 text-center"><p className="font-['Cormorant_Garamond'] text-3xl">No recipes match that search.</p><button type="button" onClick={()=>{setSearch("");setCategory("All Recipes");}} className="mt-4 text-[10px] font-semibold uppercase text-[#214d2b]">Clear filters</button></div>}</div></section>

        <section className="bg-white/35 px-4 py-16 md:px-8"><div className="mx-auto grid max-w-[1320px] gap-7 md:grid-cols-[300px_1fr]"><div><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#214d2b]">What our community is saying</p><h2 className="mt-4 font-['Cormorant_Garamond'] text-[42px] leading-[.94]">Loved by 1000+ happy coconut lovers.</h2><div className="mt-7 flex gap-2"><button type="button" onClick={()=>setReviewIndex((value)=>(value+2)%4)} className="grid size-10 place-items-center rounded-full border border-black/8"><ArrowLeft size={15}/></button><button type="button" onClick={()=>setReviewIndex((value)=>(value+1)%4)} className="grid size-10 place-items-center rounded-full border border-black/8"><ArrowRight size={15}/></button></div></div><motion.div drag="x" dragConstraints={{left:-280,right:0}} className="grid cursor-grab gap-3 md:grid-cols-3">{["Priya S.","Arjun M.","Neha R."].map((name,index)=>{const reviews=["The recipes are simple, delicious and the perfect way to include more coconut in our daily lives.","I love how every recipe feels wholesome and satisfying. My kids love them too!",".CO products make every recipe taste so fresh and natural!","A lovely, calm recipe collection that I come back to every week."];return <motion.article key={name} initial={{opacity:0,y:16}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="rounded-[24px] border border-black/6 bg-white/64 p-6 shadow-[0_14px_35px_rgba(42,27,19,.04)]"><p className="tracking-[.12em] text-[#d99b12]">★★★★★</p><p className="mt-5 min-h-[105px] text-xs leading-6">“{reviews[(index+reviewIndex)%reviews.length]}”</p><div className="mt-5 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-[#d9c6a8] font-['Cormorant_Garamond'] text-lg">{name[0]}</span><span><b className="block text-[10px]">{name}</b><span className="text-[8px] text-[#6c625a]">Verified Cook · India</span></span></div></motion.article>})}</motion.div></div></section>

        <section id="community" className="px-4 py-16 md:px-8"><div className="mx-auto grid max-w-[1320px] gap-7 md:grid-cols-[270px_1fr] md:items-center"><div><p className="text-[10px] font-semibold uppercase">Join the .CO Community</p><h2 className="mt-4 font-['Cormorant_Garamond'] text-[38px] leading-none">Share your creations and get featured.</h2><p className="mt-3 text-xl">#COCoconut</p><a href="https://www.instagram.com/cothecoconutcompany" target="_blank" rel="noreferrer" className="mt-6 inline-flex min-h-11 items-center gap-3 rounded-full bg-[#214d2b] px-5 text-[9px] font-semibold uppercase text-white">Join our community <ArrowRight size={13}/></a></div><div className="grid grid-cols-3 gap-2 md:grid-cols-5">{recipes.slice(0,5).map((recipe,index)=><motion.a href={`/recipes/${recipe.slug}`} whileHover={{y:-5}} key={recipe.slug} className={cn("group relative overflow-hidden rounded-[18px]",index===0?"aspect-[4/5]":"aspect-square")}><PremiumImage src={recipe.image} alt={`${recipe.title} community recipe`} sizes="(min-width:768px) 18vw, 31vw"/><span className="absolute right-2 top-2 grid size-8 place-items-center rounded-full bg-white/75"><Heart size={14}/></span></motion.a>)}</div></div></section>

        <TrustStrip />
        <NewsletterSection />
      </main>
      <ReferenceFooter />
      <MobileBottomNav />
    </div>
  );
}

function RecipeCard({recipe,index,saved,onSave}:{recipe:RecipeItem;index:number;saved:boolean;onSave:()=>void}){return <motion.article layout initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{delay:Math.min(index*.04,.2),ease}} whileHover={{y:-7}} className="group min-w-0 overflow-hidden rounded-[20px] border border-black/6 bg-white/58 shadow-[0_12px_34px_rgba(42,27,19,.04)]"><div className="relative aspect-[4/5] overflow-hidden"><Link href={`/recipes/${recipe.slug}`}><PremiumImage src={recipe.image} alt={recipe.title} sizes="(min-width:1024px) 15vw, 48vw"/></Link><button type="button" onClick={onSave} aria-label={`Save ${recipe.title}`} className="absolute right-2 top-2 grid size-8 place-items-center rounded-full bg-white/75"><Heart size={14} fill={saved?"currentColor":"none"}/></button></div><div className="p-3"><p className="text-[7px] uppercase tracking-[.1em] text-[#756a61]">{recipe.category} · {recipe.time} min</p><Link href={`/recipes/${recipe.slug}`} className="mt-2 block font-['Cormorant_Garamond'] text-[19px] leading-[1.05]">{recipe.title}</Link><p className="mt-3 flex justify-between text-[8px]"><b>{recipe.difficulty}</b><span className="inline-flex items-center gap-1"><Clock3 size={11}/>{recipe.time} min</span></p></div></motion.article>}

export function ProductsUsed({products}:{products:RecipeItem["products"]}){return <div className="rounded-[24px] border border-black/6 bg-white/55 p-4"><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#214d2b]">.CO products used</p><div className="mt-3 divide-y divide-black/6">{products.map((product)=><Link href={`/shop?product=${product.slug}#all-products`} key={product.name} className="flex items-center gap-3 py-3"><span className="relative block size-14 shrink-0 overflow-hidden rounded-xl bg-[#f3eee4]"><PremiumImage src={product.image} alt={product.name} sizes="56px"/></span><span className="min-w-0 flex-1"><b className="block text-[10px] leading-4">{product.name}</b><span className="text-[8px] text-[#72675e]">{product.detail}</span></span><ArrowRight size={13}/></Link>)}</div><Link href="/shop" className="mt-3 inline-flex min-h-10 w-full items-center justify-center gap-2 rounded-full border border-[#214d2b]/50 text-[9px] font-semibold uppercase"><ShoppingBag size={14}/> Shop products</Link></div>}

export function DietaryVersions({items}:{items:RecipeItem["variations"]}){return <div className="rounded-[24px] border border-black/6 bg-white/55 p-4"><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#214d2b]">Dietary versions</p><div className="mt-3 divide-y divide-black/6">{items.map((item,index)=><div key={item.name} className="flex w-full items-center gap-3 py-3 text-left"><span className="grid size-9 shrink-0 place-items-center rounded-full border border-[#214d2b]/18">{index===1?<Dumbbell size={15}/>:<Leaf size={15}/>}</span><span className="min-w-0 flex-1"><b className="block text-[10px]">{item.name}</b><span className="mt-1 block text-[8px] leading-4 text-[#72675e]">{item.detail}</span></span><ArrowRight size={12}/></div>)}</div></div>}

function TrustStrip(){return <section className="border-y border-black/6 bg-white/42 px-4 py-5 md:px-8"><div className="mx-auto grid max-w-[1320px] grid-cols-2 gap-4 md:grid-cols-5">{[[Truck,"Free delivery","On orders over ₹699"],[ChefHat,"24/7 support","We're here anytime"],[ShieldCheck,"Hassle-free returns","14-day easy returns"],[ShoppingBag,"Secure payments","100% safe & secure"],[Leaf,"Sustainable packaging","Good for you, good for Earth"]].map(([Icon,title,body])=>{const I=Icon as typeof Truck;return <div key={String(title)} className="flex items-center gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-full border border-[#214d2b]/18"><I size={17}/></span><span><b className="block text-[8px] uppercase">{String(title)}</b><span className="text-[8px] text-[#70665d]">{String(body)}</span></span></div>})}</div></section>}

