/* Local authenticated QA uses an isolated fixture API and a test-only encryption key.
 * No auth bypass or synthetic customer data is included in the app. */
const {chromium}=require(process.env.ACCOUNT_QA_PLAYWRIGHT||'/Users/fazilshersha/.codex/qa/sustainability-release/node_modules/playwright-core');
const crypto=require('node:crypto');const fs=require('node:fs');const assert=require('node:assert/strict');
const base=process.env.ACCOUNT_QA_URL||'http://localhost:3018';const output=process.env.ACCOUNT_QA_OUTPUT||'artifacts/account-qa';fs.mkdirSync(output,{recursive:true});
function cookie(){const key=crypto.createHash('sha256').update('account-local-qa-only-not-a-production-key').digest();const iv=crypto.randomBytes(12);const c=crypto.createCipheriv('aes-256-gcm',key,iv);const data=Buffer.concat([c.update(JSON.stringify({accessToken:'local-fixture-only',sub:'account-qa',email:'account-qa@example.com',name:'Afsala Khan',expiresAt:Math.floor(Date.now()/1000)+7200})),c.final()]);return [iv,c.getAuthTag(),data].map(b=>b.toString('base64url')).join('.');}
(async()=>{const browser=await chromium.launch({executablePath:process.env.ACCOUNT_QA_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const ctx=await browser.newContext();await ctx.addCookies([{name:'co_aws_session',value:cookie(),url:base,httpOnly:true,sameSite:'Lax'}]);await ctx.addInitScript(()=>{localStorage.setItem('co_cookie_consent_v1',JSON.stringify({essential:true,analytics:false,marketing:false,updatedAt:new Date().toISOString()}));localStorage.setItem('co_welcome_claimed_v1','dismissed');});
const routes=['/account','/orders','/orders/history','/orders/QA-ILLUSTRATIVE-78429','/orders/unavailable','/account/addresses','/wishlist','/saved-recipes','/profile','/account/security','/account/payments'];const widths=[1440,1280,768,430,390,375];let report=[];
const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
if(!process.env.ACCOUNT_QA_INTERACTIONS_ONLY) for(const width of widths){await page.setViewportSize({width,height:1000});for(const route of routes){const start=errors.length;const response=await page.goto(base+route,{waitUntil:'domcontentloaded',timeout:90000});await page.waitForFunction(()=>document.querySelectorAll('.co-account').length===1);await page.evaluate(async()=>{document.querySelectorAll(".co-account img").forEach(i=>i.loading="eager");for(let y=0;y<document.body.scrollHeight;y+=800){window.scrollTo({top:y,behavior:"instant"});await new Promise(r=>setTimeout(r,100));}window.scrollTo(0,0);await document.fonts.ready;});await page.waitForTimeout(250);const metrics=await page.evaluate(()=>{const root=document.querySelector('.co-account');return {overflow:document.documentElement.scrollWidth>innerWidth,brokenImages:[...root.querySelectorAll('img')].filter(i=>i.complete&&i.naturalWidth===0).map(i=>i.src),headers:document.querySelectorAll('.co-glass-header').length,footers:document.querySelectorAll('footer').length,shells:document.querySelectorAll('.co-account').length,active:document.querySelectorAll('.ac-tabs [aria-current="page"]').length,smallTargets:[...root.querySelectorAll('a,button,input,select,summary')].filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&r.height>0&&r.top<innerHeight&&r.bottom>0&&r.left>=0&&r.right<=innerWidth&&getComputedStyle(e).visibility!=='hidden'&&(r.height<43||r.width<43)&&!e.closest('.ac-product-copy,.ac-saved-copy')}).map(e=>({text:e.getAttribute('aria-label')||e.textContent.slice(0,40),width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height}))};});const name=route.replaceAll('/','-').slice(1);await page.addStyleTag({content:'.co-account .co-glass-header{position:absolute!important}'});await page.screenshot({path:`${output}/${name}-${width}.png`,fullPage:true});report.push({route,width,status:response.status(),...metrics,errors:errors.slice(start)});fs.writeFileSync(`${output}/responsive.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report.at(-1)));}}
if(!process.env.ACCOUNT_QA_INTERACTIONS_ONLY)fs.writeFileSync(`${output}/responsive.json`,JSON.stringify(report,null,2));
if(process.env.ACCOUNT_QA_RESPONSIVE_ONLY){await browser.close();return;}
await page.setViewportSize({width:390,height:900});const results=[];
await page.goto(base+'/orders/history',{waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'Next',exact:true}).click();assert.match(await page.locator('.ac-pagination').innerText(),/Page 2 of 2/);await page.getByRole('textbox',{name:'Search orders'}).fill('78429');assert.equal(await page.locator('.ac-order-row').count(),1);results.push('order search and pagination');
await page.goto(base+'/wishlist',{waitUntil:'domcontentloaded'});const initial=await page.locator('.ac-saved-card').count();await page.locator('.ac-save-heart').first().click();await page.waitForFunction(n=>document.querySelectorAll(".ac-saved-card").length===n,initial-1);await page.reload({waitUntil:'domcontentloaded'});assert.equal(await page.locator('.ac-saved-card').count(),initial-1);results.push('saved removal persists');
await page.locator('.ac-saved-card .ac-button').first().click();await page.waitForTimeout(500);const cart=await page.evaluate(()=>JSON.parse(localStorage.getItem('co-cart')||'[]'));assert.ok(cart.length);results.push('add to cart uses existing cart');
await page.goto(base+'/profile',{waitUntil:'domcontentloaded'});await page.getByLabel('Display name',{exact:true}).fill('Afsala QA');await page.locator('[name="profileLine1"]').fill('44 Legacy Profile Lane');await page.locator('[name="profileCity"]').fill('Kochi');await page.getByRole('button',{name:'Save preferences'}).click();await page.getByRole('status').filter({hasText:'Your preferences are saved.'}).waitFor();await page.reload({waitUntil:'domcontentloaded'});assert.equal(await page.getByLabel('Display name',{exact:true}).inputValue(),'Afsala QA');assert.equal(await page.locator('[name="profileLine1"]').inputValue(),'44 Legacy Profile Lane');results.push('profile and legacy delivery address save persist');
await page.goto(base+'/account/addresses',{waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'Add new address'}).click();for(const [name,value] of Object.entries({fullName:'QA Recipient',phone:'+919876543219',line1:'42 QA Lane',city:'Kochi',region:'Kerala',postalCode:'682025'}))await page.locator(`[name="${name}"]`).fill(value);await page.getByRole('button',{name:'Save address',exact:true}).click();await page.getByRole('status').filter({hasText:'Your address is saved.'}).waitFor();await page.reload({waitUntil:'domcontentloaded'});const address=page.locator('article.ac-address').filter({hasText:'QA Recipient'});assert.equal(await address.count(),1);await address.getByRole('button',{name:'Edit',exact:true}).click();await page.locator('[name="line1"]').fill('43 QA Lane');await page.getByRole('button',{name:'Save address',exact:true}).click();await page.waitForTimeout(500);assert.match(await address.innerText(),/43 QA Lane/);await address.getByRole('button',{name:'Delete',exact:true}).click();await address.getByRole('button',{name:'Confirm removal'}).click();await page.waitForTimeout(500);assert.equal(await address.count(),0);results.push('address add/edit/delete persists');
await page.request.get('http://127.0.0.1:4319/__qa/unavailable');await page.goto(base+'/account',{waitUntil:'domcontentloaded'});assert.equal(await page.locator('.ac-stats strong').allTextContents().then(values=>values.every(value=>value==='—')),true);await page.goto(base+'/orders',{waitUntil:'domcontentloaded'});assert.equal(await page.getByText('No orders yet',{exact:true}).count(),0);assert.equal(await page.locator('.ac-mini-stats strong').allTextContents().then(values=>values.every(value=>value==='—')),true);assert.equal(await page.getByText('Currently unavailable',{exact:true}).count(),2);await page.goto(base+'/wishlist',{waitUntil:'domcontentloaded'});assert.equal(await page.getByText('Your wishlist is empty',{exact:true}).count(),0);await page.goto(base+'/account/addresses',{waitUntil:'domcontentloaded'});assert.equal(await page.getByText('No addresses yet',{exact:true}).count(),0);await page.goto(base+'/profile',{waitUntil:'domcontentloaded'});await page.getByText('Saved address count is currently unavailable.').waitFor();results.push('API failures remain unavailable, never empty or zero');await page.request.get('http://127.0.0.1:4319/__qa/available');
await page.goto(base+'/account/security',{waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'Sign out from this device'}).click();await page.waitForURL(base+'/');await page.goto(base+'/orders/history');assert.match(page.url(),/login\?redirect=%2Forders%2Fhistory/);results.push('logout and protected destination redirect');
const anon=await browser.newContext();const anonPage=await anon.newPage();for(const route of routes){await anonPage.goto(base+route,{waitUntil:'domcontentloaded'});assert.match(anonPage.url(),/\/login\?redirect=/);}results.push('all account routes protected');
fs.writeFileSync(`${output}/interactions.json`,JSON.stringify({results},null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
