"use client";
import Image from "next/image";
import { useState } from "react";
import { ArrowRight,Check,ChevronDown,MapPin,Minus,Plus,QrCode,Recycle,Search,ShieldCheck,Sprout } from "lucide-react";
import { ButtonLink,DarkShell,Eyebrow,Newsletter,RD,Scene } from "@/components/reference/DarkReference";
import { sustainabilityImpact } from "@/lib/content/impact";
import { transparentProductAssets } from "@/lib/website-assets";
const A=RD.sustainability;
const principles=[["01","Trace the source","Know where every coconut comes from, and who harvested it."],["02","Use the whole coconut","From water to shell, every part has a purpose."],["03","Measure the outcome","Track people, product and planet with real data."],["04","Show the evidence","Open records and proof you can explore."]];
const streams=[
 ["Water","~25%",[[".CO Coconut Water","Hydration, naturally.","water"],["Coconut Milk","Plant-based nourishment.","kitchen-milk"]]],
 ["Kernel / Pulp","~31%",[["Virgin Coconut Oil","Pure. Versatile. Essential.","kitchen-oil"],["Coconut Flour","Natural. Gluten-free.","kitchen-flour"]]],
 ["Shell","~17%",[["CoCarbon","Activated carbon by .CO",null],["Biochar","A future soil-amendment stream",null],["Charcoal & Crafts","Traditional uses, reimagined.",null]]],
 ["Husk","~27%",[["Soil Application","A future regenerative pathway",null],["MRV / Carbon Accounting","Measured. Reported. Transparent.",null]]]
] as const;
export function ReferenceSustainabilityPage(){
 const [batch,setBatch]=useState(""); const [trace,setTrace]=useState<"idle"|"missing">("idle"); const [quantity,setQuantity]=useState(24); const [calculated,setCalculated]=useState(false); const [open,setOpen]=useState("Water");
 const sim=sustainabilityImpact.simulationBasis; const coconut=(quantity*sim.coconutEquivalentPerUnit).toFixed(1); const plastic=(quantity*sim.plasticAvoidedPerUnitKg).toFixed(2); const co2=(quantity*sim.co2eReducedPerUnitKg).toFixed(2);
 return <DarkShell className="rd-sustainability">
  <section className="sustain-hero"><Scene priority src={`${A}COCONUT HERO IMAGE.png`} alt="Pollachi coconut landscape at sunset"/><div><Eyebrow>Our impact</Eyebrow><h1>Nothing wasted.<br/>Everything<br/><em>accounted for.</em></h1><p>Good for you, accountable to the system. Follow our coconuts from the tree to you.</p><ButtonLink href="#trace">Trace a batch</ButtonLink> <ButtonLink href="#flow" ghost>Follow the coconut</ButtonLink><div className="hero-location"><MapPin/> Pollachi · Tamil Nadu · India</div></div></section>
  <section className="rd-section principles"><Eyebrow>Our sustainability principle</Eyebrow><h2>A coconut shouldn’t disappear<br/>when the bottle is filled.</h2><p>We source responsibly, use every part with purpose, measure what matters, and share proof you can trust.</p><div>{principles.map(([n,t,b])=><article key={n}><i>{n}</i><span><Sprout/></span><h3>{t}</h3><p>{b}</p></article>)}</div></section>
  <section id="trace" className="rd-section trace-section"><div><Eyebrow>Trace your coconut</Eyebrow><h2>From one batch,<br/>back <em>to the farm.</em></h2><p>Enter your batch code or scan the QR to follow its recorded journey.</p><form className="trace-form rd-glass" onSubmit={e=>{e.preventDefault();setTrace("missing")}}><label htmlFor="batch">Trace a batch</label><div><input id="batch" value={batch} onChange={e=>setBatch(e.target.value)} placeholder="Enter batch code" required/><Search/></div><button>Trace batch <ArrowRight/></button><button type="button" className="qr"><QrCode/> Scan QR</button>{trace==="missing"&&<p role="status">No published traceability record matches this code yet. Check the code or contact support.</p>}</form></div><div className="trace-map rd-glass"><div className="map-lines" aria-label="Stylised Pollachi sourcing map"><span>Pollachi</span>{[1,2,3,4,5].map(n=><i key={n}/>)}</div><aside><b>Farming zone</b><small>Pollachi, Tamil Nadu</small><small>Live batch details appear only after a verified record is found.</small></aside><ol>{["Harvested","Collected","Quality checked","Processed","Packed","Dispatched"].map(x=><li key={x}><span/><b>{x}</b></li>)}</ol></div></section>
  <section className="rd-section seasonal rd-glass"><div><h2>Coconuts have a rhythm.<br/><em>We follow it.</em></h2><p>Seasonal sourcing, intentionally rooted in real cycles.</p></div><svg viewBox="0 0 1000 270" role="img" aria-label="Illustrative seasonal harvest activity and product availability chart"><defs><linearGradient id="harvest" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#d88b43" stopOpacity=".5"/><stop offset="1" stopColor="#d88b43" stopOpacity="0"/></linearGradient></defs><path d="M0 190 C120 190 135 55 280 75 S430 200 555 185 S700 70 820 85 S920 190 1000 190 L1000 220 L0 220Z" fill="url(#harvest)"/><path d="M0 190 C120 190 135 55 280 75 S430 200 555 185 S700 70 820 85 S920 190 1000 190" fill="none" stroke="#db8f48" strokeWidth="3"/><path d="M0 205 C120 170 210 205 300 165 S460 210 570 175 S710 205 820 155 S930 180 1000 168" fill="none" stroke="#9c9d62" strokeWidth="3"/><g>{["JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC"].map((m,i)=><text key={m} x={i*87+10} y="250" fill="#c9aa89" fontSize="15">{m}</text>)}</g></svg><small>Seasonal pattern shown as an operating illustration; final procurement curves require approved farm records.</small></section>
  <section id="flow" className="rd-section flow-section"><div className="flow-heading"><Eyebrow>Nothing stops at the bottle</Eyebrow><h2>One coconut.<br/><em>Many lives.</em></h2><p>We follow each part through a circular system, while clearly separating live streams from future pathways.</p></div><Scene src={`${A}NOTHING WASTED EVERYTHING ACCOUNTED FOR.png`} alt="Split coconut with warm amber energy"/><div className="flow-canvas"><div className="flow-source rd-glass"><b>One coconut</b><strong>100% utilised</strong><Recycle/></div>{streams.map(([name,pct,destinations])=><div className="stream-row" key={name}><button onClick={()=>setOpen(name)} className={`stream-node rd-glass ${open===name?"active":""}`}><b>{name}</b><span>{pct}</span></button><div className="flow-path"/><div className="destinations">{destinations.map(([title,desc,asset])=><article className="rd-glass" key={title}><div><h3>{title}</h3><p>{desc}</p><small>{name==="Water"||name==="Kernel / Pulp"?"Current product destination":"Planned / evidence pending"}</small></div>{asset&&<Image src={transparentProductAssets[asset].src} alt={title} width={70} height={90} className="object-contain"/>}<Plus/></article>)}</div></div>)}</div><aside className="methodology rd-glass"><Eyebrow>{open} stream</Eyebrow><p>Methodology and verification details appear here only when an approved evidence record is available.</p><ButtonLink href="/contact" ghost>Request methodology</ButtonLink></aside></section>
  <section className="rd-section impact-section"><div className="impact-heading"><Eyebrow>Your impact</Eyebrow><h2>What does <em>your</em><br/>coconut leave behind?</h2><p>Explore the approved launch simulation. This is not historical or verified impact reporting.</p></div><div className="impact-still"><Image src={transparentProductAssets.water.src} alt=".CO Coconut Water" fill sizes="240px" className="object-contain"/><Image src={transparentProductAssets["kitchen-oil"].src} alt=".CO Virgin Coconut Oil" fill sizes="240px" className="object-contain"/></div><div className="impact-calculator rd-glass"><div><Eyebrow>Illustrative calculator</Eyebrow><label>1. Product<select><option>.CO Water</option></select></label><label>2. Quantity<div className="quantity"><button onClick={()=>setQuantity(q=>Math.max(1,q-1))}><Minus/></button><b>{quantity}</b><button onClick={()=>setQuantity(q=>q+1)}><Plus/></button></div></label><button className="rd-button" onClick={()=>setCalculated(true)}>Calculate illustration <ArrowRight/></button></div><div><h3>Your illustrative results</h3><p>{sustainabilityImpact.disclosure}</p>{calculated?<div className="impact-results">{[[coconut,"Coconut equivalents sourced"],[plastic+" kg","Plastic avoided (modelled)"],[co2+" kg","CO₂e reduced (modelled)"]].map(([v,l])=><span key={l}><b>{v}</b><small>{l}</small></span>)}</div>:<div className="impact-empty">Choose a quantity and calculate to view the design-stage scenario.</div>}<small>Modelled from repository simulation assumptions; not a verified product claim.</small></div></div></section>
  <section className="people-section"><Scene src={`${A}IMPACT SHOULD REACH PEOPLE TOO.png`} alt="Women working with coconuts at a community processing site"/><div><Eyebrow>The people in the system</Eyebrow><h2>Impact should<br/>reach <em>people too.</em></h2><p>Behind every .CO product is a community of skilled people. Public metrics will appear after evidence review.</p><ButtonLink href="/about">Meet our communities</ButtonLink></div><aside className="rd-glass">{["Women-led enterprise structure","Pollachi sourcing anchor","VAP network planned for phased rollout","Training data pending publication"].map(x=><span key={x}><ShieldCheck/><b>{x}</b></span>)}</aside></section>
  <section className="rd-section receipts"><div><Eyebrow>The receipts</Eyebrow><h2>Don’t take<br/>our word for it.</h2><p>Evidence should be open and verifiable. We publish only what has a production record.</p></div><div className="receipts-table rd-glass">{[["Corporate structure","Incorporation records","Filed"],["Trademark","Application record","Filed"],["Origin traceability","Protocol and batch map","In progress"],["Waste-stream measurement","Audit and methodology","Not published"],["Environmental claims","LCA / field data","Not verified"]].map(([a,e,s])=><div key={a}><b>{a}</b><span>{e}</span><i>{s}</i><ChevronDown/></div>)}</div></section>
  <section className="rd-section roadmap"><div><Eyebrow>Next</Eyebrow><h2>Better <em>isn’t</em> finished.</h2><p>Real change follows seasons, not shortcuts.</p></div><div className="roadmap-board rd-glass">{[["Now",["Pollachi contract-farm anchor","UHT co-packer readiness","Baseline measurement"]],["Next",["Batch-level traceability","VAP pilot rollout","Quarterly reporting"]],["Later",["Verified impact dashboard","Recovery at scale","Regional livelihood index"]]].map(([phase,items])=><article key={phase as string}><h3>{phase}</h3>{(items as string[]).map(x=><p key={x}><Check/> {x}</p>)}</article>)}</div></section>
  <section className="closing-source"><Scene src={`${A}A BETTER COCONUT SYSTEM STARTS AT THE SOURCE.png`} alt="Coconut growers and community at the source"/><div><h2>A better coconut system<br/>starts at the source.</h2><p>To the people who grow it and the communities who care for it.</p><ButtonLink href="#trace">Trace your batch</ButtonLink></div></section><Newsletter/>
 </DarkShell>;
}
